### ISSUE TITLE
Owning of geoserver data

### ISSUE THREAD

**Issue by wohnout** [SDI4Apps/cloud-platform#13]
replace line 414
chown -R www-data:www-data /home/ubuntu/liferay-portal-6.2-ce-ga6/tomcat-7.0.62/webapps/geoserver/data

with 

cd /home/ubuntu/liferay-portal-6.2-ce-ga6/tomcat-7.0.62/webapps/geoserver/data
find -type d -exec setfacl -m u:www-data:rwx -m g:www-data:rwx -d -m u:www-data:rwx -d -m g:www-data:rwx {} \;
find -type f -exec setfacl -m u:www-data:rwx -m g:www-data:rwx {} \;

**Comment by martin-kuba** [comment]
I do not see the point, but added anyway.
