### ISSUE TITLE
Virtuoso install

### ISSUE THREAD

**Issue by wohnout** [SDI4Apps/cloud-platform#14]
Extend packages of:
aptitude install unixodbc libmono-corlib2.0-cil libmono-system-data2.0-cil libmono-system2.0-cil

Download http://packages.sdi4apps.eu/virtuoso_deb.tar.xz

and install all packages from that tar

Extend apache site with

```
ProxyPass /sparql           http://localhost:8890/sparql
```

**Comment by wohnout** [comment]
Create admin user with password somepass (will be asked in ncurses window during installation)

**Comment by martin-kuba** [comment]
solved in 843e4ef
