### ISSUE TITLE
Load data to virtuoso

### ISSUE THREAD

**Issue by wohnout** [SDI4Apps/cloud-platform#15]
Download http://packages.sdi4apps.eu/virtuoso_data.tar.xz

Extract it to /tmp and run

isql-vt 1111 dba somepass exec="ld_dir ('/tmp/rdf', 'Zemgale_S4a.rdf', 'http://www.sdi4apps.eu/poi.rdf');"
isql-vt 1111 dba somepass exec="rdf_loader_run(log_enable=>3);"

isql-vt 1111 dba somepass exec="ld_dir ('/tmp/rdf', 'LV.rdf', 'http://www.sdi4apps.eu/poi.rdf');"
isql-vt 1111 dba somepass exec="rdf_loader_run(log_enable=>3);"

isql-vt 1111 dba somepass exec="ld_dir ('/tmp/rdf', 'LV_OSM.rdf', 'http://www.sdi4apps.eu/poi.rdf');"
isql-vt 1111 dba somepass exec="rdf_loader_run(log_enable=>3);"

**Comment by martin-kuba** [comment]
solved in 843e4ef
