### ISSUE TITLE
Status manager

### ISSUE THREAD

**Issue by wohnout** [SDI4Apps/cloud-platform#16]
Rename template files of configs by removing -template in folder /data/wwwlibs/statusmanager

Uncomment and edit in statusmanager.ini lines

```
[csw]
# catalogue service
url="http://localhost/php/metadata/csw/index.php"
```

change line 2 in res/HsAuth.php to

```
define("LIFERAY_VALIDATE_URL", "http://localhost/sso-portlet/service");
```

aptitude install sqlite3

create db in data/ by

```
sqlite3 data.sqlite < data.sql
```

chown it to www-data

**Comment by martin-kuba** [comment]
solved in commit e7d2bdd
