### ISSUE TITLE
Liferay

### ISSUE THREAD

**Issue by wohnout** [SDI4Apps/cloud-platform#9]
DB from http://packages.sdi4apps.eu/liferay.sql.xz

Change values in /home/ubuntu/liferay-portal-6.2-ce-ga6/tomcat-7.0.62/bin/setenv.sh
-Xmx1536m -XX:MaxPermSize=512m
(originally was 1024m and 256m) 

Replace /home/ubuntu/liferay-portal-6.2-ce-ga6/tomcat-7.0.62/webapps/ROOT/WEB-INF/classes/portal-ext.properties with

http://packages.sdi4apps.eu/portal-ext.properties.xz

**Comment by martin-kuba** [comment]
Done.
